Add balance command
matter-labs/zksync-cli pull request #79
Opened 2023-11-17 15:47 UTC by jrchatruc

# What :computer: 

# Why :hand:

# Evidence :camera:

# Notes :memo:

2023-11-17 17:43 UTC, JackHamer09 requested changes
Should we also ask for which token to get balance to? ETH or ERC20
And then if ERC20 is selected we also ask for address of the token.
Would be useful to have something like that :)
Not required for this PR tho..

2023-11-17 17:43 UTC, JackHamer09 commented on src/commands/wallet/command.ts
> +export default Program.command("wallet").description("Manage wallet related features for L2 and L1");
For now there is no L1 features.
So we should either not mention L1 and just say `Manage zkSync wallet related features`
or
Add possibility to choose L1 network in the list. For example:
```
❯ zkSync Era Testnet 
  zkSync Era Mainnet 
  Local Dockerized node
  ---
  Ethereum Mainnet
  Ethereum Goerli Testnet
```

2023-11-17 17:43 UTC, JackHamer09 commented on src/commands/wallet/balance.ts
> +        Logger.info(`\n${bigNumberToDecimal(balance)} ETH`);
Let's say `${selectedChain.name} Balance: XX ETH`

2023-11-17 17:43 UTC, JackHamer09 commented on src/commands/wallet/balance.ts
> +        const toChain = l2Chains.find((e) => e.network === options.chain);
Let's call it `selectedChain`

2023-11-17 17:43 UTC, JackHamer09 commented on src/commands/wallet/balance.ts
> +        const Provider = getL2Provider(options.l2RpcUrl ?? toChain!.rpcUrl);
Let's not create uppercase variables

2023-11-17 17:43 UTC, JackHamer09 commented on src/commands/wallet/balance.ts
> +    accountOption,
Try to properly setup prettier so the code is properly styled

2023-11-17 17:43 UTC, JackHamer09 commented on src/common/options.ts
> +export type BalanceOptions = DefaultOptions & {
I don't think we should keep `BalanceOptions` in this file. Let's move it to balance.ts where it is used.

2023-11-20 14:17 UTC, jrchatruc commented
> Should we also ask for which token to get balance to? ETH or ERC20 And then if ERC20 is selected we also ask for address of the token. Would be useful to have something like that :) Not required for this PR tho..

That would be very useful indeed, we'll add it on a subsquent PR!

2023-11-20 14:18 UTC, jrchatruc commented
Addressed all the commends above here [aef66ef](https://github.com/matter-labs/zksync-cli/pull/79/commits/aef66ef45749923c48763bc356c0c36a87e32b41) and here [2e88921](https://github.com/matter-labs/zksync-cli/pull/79/commits/2e8892186e7e3538e4433467d4dae6970b90cf63). In regards to this

```
For now there is no L1 features.
So we should either not mention L1 and just say Manage zkSync wallet related features
or
Add possibility to choose L1 network in the list.
```

For now I just changed the description to not mention L1, we might add L1 features in the future.

2023-11-27 12:39 UTC, closed without merging